import { Button } from "./Button"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by `figma connect create` --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  Button,
  "https://www.figma.com/file/azv53zX7Jry7jQUQqMGzqf/FOCUS_-Core-Library?type=design&node-id=5-302&mode=dev",
  {
    props: {
      icon: figma.instance("icon"),
      label: figma.string("label"),
      showIcon: figma.boolean("showIcon"),
      variant: figma.enum("variant", {
        primary: "primary",
        secondary: "secondary",
        destructive: "destructive",
        hollow: "hollow",
      }),
      size: figma.enum("size", {
        default: "default",
        large: "large",
      }),
      disabled: figma.boolean("disabled"),
      fullWidth: figma.boolean("fullWidth"),
    },
    example: (props) => <Button />,
  },
)
